### ISSUE TITLE
Implementation of the asset management sub-system.

### ISSUE THREAD

**Issue by kaisc** [kaisc/crayon#9]
This issue is a part of #6 which involving the asset management sub-system. An asset is a file on disk, stored with some specified formats. For example, texture files, model files and entity description files are all assets.

To make a plain resource produced by artist actually be used in game or project, there are many topics should be discussed carefully. This is the first version of the designs, the final implementation could change rapidly, and any kind of suggestions are always welcome.

### General discussion
__Assets stored in various file format__. We should provide corresponding loaders to parse them into memory with meaningful information. BTW, its impossible to maintain loaders for most of the common files, not to mention some kind of user custom file format. Its vital to have a flexible mechanism that allows user to provide their own custom loaders.

__Assets can be archived with different file system__. Such like common ZIP file besides plain forlder, its convenient to provide a virtal archive system that lets us define multiple "file systems" with various backing stores, then merge them together.

__Assets might have dependencies__. For example, a simple terrain asset could be composed of a normal map, a height map and a diffuse texture. Its tedious and error-prone to manually manage the dependencies. So we need some kind of mechanism to resolve the dependent relationships.

__Assets might be referred by various owner in same time__. For example a texture sheet might be used in hundreds UI elements. For the sake of memory usage, we need some kind of identification to make sure that we have only one copy in the meantime.

Many software use `Path` as identification, it works fine before we refining the name or file structure of assets, and `Path` itself is not platform independent yet. Its better to have a general GUID mapped to asset in my view.

__Assets have its own lifecycle during the whole runtime__. They are loaded into/ unloaded from memory at specific and defined times. To reduce loading times and manage and application's memory footprint, its important to track the resource lifecycle. This could be addressed by reference counting technique.

__Reading from disk is much more expensive than in memory operations__. So its good to have a configuable cache to keep hot file staying in memory.

### Implementation
TODO

### Checklist
- [x] Virtual file system with default supports for plain folder and ZIP file.
- [x] Reference counting based lifecycle management.
- [x] Identify resource at runtime with GUID.
- [x] File requests dispatch and loader trait. It should be structured in a way to easily be extended by user.
- [x] Builtin loaders for common file formats.
- [x] Default cache mechanism based on LRU strategy.

**Comment by sjaustirni** [comment]
Firstly, I love how much time and energy you put into making this gem better. Kudos to you for that! :+1: 
Anyway, back to "bussiness" now :smile: 

I think you're mixing two things now (or maybe you're not mixing it, but I feel the urge to clarify this :smile:) :
- **VFS** (virtual) filesystem - an API dedicated to general access of arbitrary files in various locations (game folder, user folder, etc... as in ggez [filesystem.rs](https://github.com/sjaustirni/ggez/blob/master/src/filesystem.rs)), possibly in an archive like ZIP. Here we should probably also tackle LRU caching.
- **AM** asset management - an API dedicated to clever managing assets within the game (here's asset lifetime, dependencies, ownership and references...)

The most important fact is that VFS doesn't know about the format of the requested file. AM just passes in the path, VFS attempts to find it and then it returns the data. It's important to note that VFS doesn't own anything. That's not its job.
The data is then returned to an AM loader which parses it (AM does know about the file format), it creates a `Handle` (be it GUID or anything else) and returns it. AM owns the data.
This also means that you have to create loaders for every type you need in your game (which is a good thing if you ask me).
For instance, we could provide `Image` loader. User would provide `NormalMap`, `HeightMap` and `DiffuseTexture` loaders, all of which would call `Image` loader and perform some operation on the data, like a pipe. Finally, `Terrain` loader would call all three loaders above and return the processed data to the user when itself called.
This system can handle arbitrary data in a very specific way. This also resolves the dependency problem, because if a loader can't find the specified file, user decides what to do (return `None`, throw and exception, silently recover...). It's easily understandable, simple to write for the user (maybe we could even provide some convenient functions if necessary) and we don't have to write a dependency manager ourselves (which probably wouldn't be as flexible as the pipe system anyway).

Those are my 2¢. I am not too skilled in Rust, so I welcome any comments on implementation and/or why is this a shitty idea in general. 

[diagram.pdf](https://github.com/kaisc/crayon/files/1066294/diagram.pdf)
![diagram-1](https://user-images.githubusercontent.com/22116610/27009387-e81e3c30-4e8c-11e7-855a-2cf8ecc45b33.png)

**Comment by kaisc** [comment]
Indeed, its almost impossible to write a flexible dependencies manager without a bunch of giant authoring tools, just like Unity3d or Unreal, thats not what we should do right now.

And the graph makes a great example to show how the loader works. But how could `TerrainLoader` to figure out whether a texture has been loaded into memory? This might cause duplicated copies of same assets. Thats why I'm planing to build loader trait base on __AM__.

**Comment by sjaustirni** [comment]
No, it's not the job of `TerrainLoader` to figure out if the requested texture is already in the memory. It's the job of `DiffuseTextureLoader`.

Again, I am not too skilled in Rust, so I will give you an example how I would do it in C++.

Every loader owns a container of things it loads. For instance, `DiffuseTextureLoader` owns a container of `DiffuseTexture` instances. When the loader is asked for a "snowy" texture, it firstly checks if it exists in the container and only if it's not there it continues upwards the diagram. If all the `Handle`s go out of scope, the entry in the container is marked for deletion and the **LRUCM** (LRU caching mechanism) is noticed of it. Once the memory runs out, the LRUCM starts to delete the entries in its FIFO queue. Note that *mark for deletion* and *delete* are two different methods with different consequences. Also, if the memory doesn't run out before the entry marked for deletion is reused, that entry needs to be removed from the LRUCM queue. 

I assume it could be implemented in the loader trait mentioned by you, I just think it shouldn't be the concern of `TerrainLoader` to make sure `DiffuseTexture` objects are reused, but rather that loaders should be reusing their already-loaded instances of the respective types, if possible.

**Comment by kaisc** [comment]
Totally agree with you. Thats how loader should works. It might have some difference in implementation due to the strict lifetime checks by rust.
